# require 'rake/testtask'

# Rake::TestTask.new do |t|
#  t.libs << "tests"
#  t.test_files = FileList['tests/test*.rb']
#  t.verbose = true
# end

require 'rake/testtask'

Rake::TestTask.new do |t|
  t.libs << 'test'
end

desc "Run tests"
task :default => :test